// @ts-check

/**
 * @file Astro + Starlight configuration: site identity, hosting paths, sidebar, plugins.
 *
 * Analogy: this is `angular.json` and `application.yml` in one file. It decides how the
 * site builds and where it will be served from.
 *
 * Hosting paths come from environment variables so the same code works in three places:
 *   - Local dev:          nothing set  -> served at http://localhost:4321/
 *   - GitHub Pages (CI):  the deploy workflow sets SITE_URL and BASE_PATH from the
 *                         `actions/configure-pages` outputs, e.g.
 *                         SITE_URL=https://<user>.github.io  BASE_PATH=/<repo>
 *   - Custom domain later: the same workflow outputs BASE_PATH="" and it just works.
 * No repo name is hard-coded anywhere, so renaming the repo needs no code change.
 */
import { existsSync } from 'node:fs';
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import starlightLinksValidator from 'starlight-links-validator';
import { DOMAINS, GROUPS } from './src/domains.mjs';
import { satteri } from '@astrojs/markdown-satteri';
import { baseLinksPlugin } from './src/plugins/base-links.mjs';

/** Full origin the site is served from. Used for canonical URLs and the sitemap. */
const site = process.env.SITE_URL || undefined;

/**
 * Path prefix the site lives under. `||` (not `??`) on purpose: configure-pages outputs
 * an empty string for root sites, and an empty string must fall back to "/".
 */
const base = process.env.BASE_PATH || '/';

/** Folder that holds every page, relative to the project root. */
const DOCS_DIR = './src/content/docs';

/**
 * Build one guide's sidebar entries from the files that actually exist.
 *
 * Why not a single `autogenerate` for the whole guide folder: Starlight labels
 * autogenerated sub-folders with their raw folder names ("levels", "walkthroughs"),
 * and there's no option to rename them. Listing the sections explicitly gives proper
 * labels, and checking the filesystem first keeps empty sections out of the sidebar.
 *
 * @param {string} slug Guide folder name from `src/domains.mjs`, e.g. "aws".
 * @returns {Array<object>} Sidebar items: Overview, then Levels, Concepts, Cheat sheet, Walkthroughs when present.
 */
function guideItems(slug) {
  const dir = `${DOCS_DIR}/${slug}`;
  /** @type {Array<object>} */
  const items = [{ label: 'Overview', slug }];
  if (existsSync(`${dir}/levels`)) items.push({ label: 'Levels', items: [{ autogenerate: { directory: `${slug}/levels` } }] });
  if (existsSync(`${dir}/concepts`)) items.push({ label: 'Concepts', items: [{ autogenerate: { directory: `${slug}/concepts` } }] });
  if (existsSync(`${dir}/cheat-sheet.md`) || existsSync(`${dir}/cheat-sheet.mdx`)) items.push({ label: 'Cheat sheet', slug: `${slug}/cheat-sheet` });
  if (existsSync(`${dir}/walkthroughs`)) items.push({ label: 'Walkthroughs', items: [{ autogenerate: { directory: `${slug}/walkthroughs` } }] });
  return items;
}

/**
 * Sidebar = "Start here" + one section per group, each holding one collapsed group per guide.
 * Adding a domain in `src/domains.mjs` adds it here. Order inside Levels and Walkthroughs
 * comes from each page's `sidebar.order` frontmatter.
 *
 * Note: the sidebar is computed when the config loads. After creating a new Levels or
 * Walkthroughs folder, restart `npm run dev` for it to appear.
 */
const sidebar = [
  { label: 'Start here', items: ['about/how-guides-work'] },
  ...GROUPS.map((group) => ({
    label: group,
    items: DOMAINS.filter((d) => d.group === group).map((d) => ({
      label: d.label,
      collapsed: true,
      items: guideItems(d.slug),
    })),
  })),
];

export default defineConfig({
  site,
  base,
  markdown: {
    // Sätteri is Astro 7's default Markdown processor; we pass it explicitly only to add
    // one plugin that prefixes `base` onto root links like [AWS](/aws/). See the plugin file.
    processor: satteri({ mdastPlugins: [baseLinksPlugin(base)] }),
  },
  integrations: [
    starlight({
      title: 'Zero to Expert',
      description: 'Field guides from first steps to mastery: tech, trades, and survival.',
      customCss: ['./src/styles/theme.css'],
      // Adds the "not fact-checked yet" banner from each page's `status`.
      routeMiddleware: './src/routeData.ts',
      sidebar,
      plugins: [
        // Fails the build on any broken internal link or missing #heading anchor.
        starlightLinksValidator(),
      ],
    }),
  ],
});
